#! /home/jscott/.pyenv/shims/python

from sys import argv
from typing import List


def parse_crates(input_lines: List[str]) -> List[List[str]]:
    crates = []

    # find out the x-axis
    previous_line = ""
    for line in input_lines:
        if line == "":
            break
        previous_line = line

    for line in input_lines:
        if line == "":
            break
        line_chunks = list(line)

        stack = []
        for i in range(1, len(line_chunks), 2):
            stack.append(line_chunks[i])

    return list(filter(lambda x: x != "", list(previous_line)))[-1]


def prompt_one(input_lines: List[str]):
    return parse_crates(input_lines)


def prompt_two(input_lines: List[str]):
    pass


if __name__ == "__main__":
    if len(argv) != 3:
        print("use like './main.py {problem number} {environment}'")
        exit(1)

    [program_name, problem, environment] = argv

    if problem not in ["1", "2"]:
        print("problem must be in [1, 2]")
        exit(1)

    if environment not in ["test", "answer"]:
        print("environment must be in [test, answer]")
        exit(1)

    problem_input = f'{"test" if environment == "test" else "input"}-{problem}.txt'

    input_lines = []

    with open(problem_input, 'r') as f:
        input_lines = [line.rstrip() for line in f]

    if problem == "1":
        print(prompt_one(input_lines))
    else:
        print(prompt_two(input_lines))
